obj-$(CONFIG_POWER_EN)		+= power_en.o
obj-$(CONFIG_LED_GPIO)      	+=led-gpio.o
obj-$(CONFIG_RP_GPIO_CTRL)      += rp_gpio_ctrl.o
obj-$(CONFIG_RP_CONFIG)  	+= rp_config.o
obj-$(CONFIG_RP_GPIO)          += rp_gpio.o